export const LEAGUES = [
  {
    id: 39,
    name: "Premier League",
    country: "England",
    slug: "premier-league",
    emoji: "🏴",
    logo: "https://media.api-sports.io/football/leagues/39.png",
  },
  {
    id: 140,
    name: "La Liga",
    country: "Spain",
    slug: "la-liga",
    emoji: "🇪🇸",
    logo: "https://media.api-sports.io/football/leagues/140.png",
  },
  {
    id: 135,
    name: "Serie A",
    country: "Italy",
    slug: "serie-a",
    emoji: "🇮🇹",
    logo: "https://media.api-sports.io/football/leagues/135.png",
  },
  {
    id: 78,
    name: "Bundesliga",
    country: "Germany",
    slug: "bundesliga",
    emoji: "🇩🇪",
    logo: "https://media.api-sports.io/football/leagues/78.png",
  },
  {
    id: 61,
    name: "Ligue 1",
    country: "France",
    slug: "ligue-1",
    emoji: "🇫🇷",
    logo: "https://media.api-sports.io/football/leagues/61.png",
  },
  {
    id: 88,
    name: "Eredivisie",
    country: "Netherlands",
    slug: "eredivisie",
    emoji: "🇳🇱",
    logo: "https://media.api-sports.io/football/leagues/88.png",
  },
  {
    id: 94,
    name: "Primeira Liga",
    country: "Portugal",
    slug: "primeira-liga",
    emoji: "🇵🇹",
    logo: "https://media.api-sports.io/football/leagues/94.png",
  },
] as const;